pipeline{
    agent any

    stages{

        stage('build stage'){
            steps{
                echo 'This is build stage..!'
            }
        }

        stage('test stage'){
            steps{
                echo 'This is test stage..!'
            }
        }

        stage('deploy stage'){
            steps{
                echo 'This is deploy stage..!'
            }
        }
        
    }
}
